### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/loader-nodejs#3]
There is a name fix on master that isn't released yet. Currently when the `aurelia-boostrapper` tries to use this loader it crashes because of this.

**Comment by EisenbergEffect** [comment]
@MeirionHughes Are we good to do a new release?

**Comment by niieani** [comment]
Yes, we are!

**Comment by EisenbergEffect** [comment]
Got it 😀

**Comment by MeirionHughes** [comment]
I guess its technically a breaking change due to: https://github.com/aurelia/loader-nodejs/commit/2a68ef982aff1ccfa81978756af3c5a04f6ba280#diff-7b09e8962a435a5614ff38f0cbd28551L80

**Comment by EisenbergEffect** [comment]
Tha makes me very say. We have to bump to 2.0 because of a typo.... ?

**Comment by stoffeastrom** [comment]
Agree, I would rather say it's a bug fix since it hasn't been working ;)

**Comment by MeirionHughes** [comment]
yeah, just up the patch; there are only a dozen or so downloads on npm.

**Comment by EisenbergEffect** [comment]
Ok, cool. I'll get it done.
