### ISSUE TITLE
Fix Redeclaring imports - LoaderPlugin to support Typescript 3.7

### ISSUE THREAD

**Issue by vvnsk** [aurelia/loader-nodejs#6]
**I'm submitting a bug report**

- **Library Version: **
1.0.1

Please tell us about your environment:

- **Operating System: **
Windows 10

- **Node Version:**
 8.9.4

- **NPM Version: **
5.6.0

- **JSPM OR Webpack AND Version :**
Webpack

- **Language: **
TypeScript 3.7

**Current behavior**: Since upgrading to TypeScript 3.7, I am getting the following error during transpilation:
 Error in node_modules/aurelia-loader-nodejs/dist/aurelia-loader-nodejs.d.ts(2,41): error TS2440: Import declaration conflicts with local declaration of ‘LoaderPlugin'.

**Expected/desired behavior:**
TypeScript 3.7 transpilation to work.

**Triage:**

A bug fix introduced in TypeScript 3.7 seems to be the cause of the issues here under the 'Local and Imported Type Declarations Now Conflict' section:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#local-and-imported-type-declarations-now-conflict

**Comment by vvnsk** [comment]
Closing the issue as the PR to address the issue has been merged.

**Comment by vvnsk** [comment]
@EisenbergEffect Can we have a new version with the new pull request merged in.

**Comment by EisenbergEffect** [comment]
It was released yesterday. You should be able to get it from npm. I

**Comment by vvnsk** [comment]
Was able to get it from npm. Thanks!
